// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../src/layouts/404.vue')['default']
    AccountHeader: typeof import('./../src/modules/widgets/AccountHeader.vue')['default']
    Dashboard: typeof import('./../src/layouts/dashboard.vue')['default']
    DashboardHeader: typeof import('./../src/layouts/dashboard/widgets/DashboardHeader.vue')['default']
    Default: typeof import('./../src/layouts/default.vue')['default']
    GoPathBtn: typeof import('./../src/modules/widgets/GoPathBtn.vue')['default']
    LocaleSelect: typeof import('./../src/modules/widgets/LocaleSelect.vue')['default']
    NotificationBtn: typeof import('./../src/modules/widgets/NotificationBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggler: typeof import('./../src/modules/widgets/ThemeToggler.vue')['default']
  }
}
